# Generated by Django 4.2.30 on 2026-05-16 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('icono', models.CharField(default='tag', max_length=50)),
                ('color_hex', models.CharField(default='#6366f1', max_length=7)),
                ('es_predefinida', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gastos',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='GastoParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto_correspondiente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='expenses.gasto')),
            ],
            options={
                'db_table': 'gasto_participantes',
            },
        ),
    ]
