# Generated by Django 4.2.30 on 2026-05-16 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastoparticipante',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gasto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.categoria'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gasto',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='groups.grupo'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='pagado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_pagados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='gastoparticipante',
            unique_together={('gasto', 'usuario')},
        ),
    ]
